version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=blocks_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
