---
openapi: 3.0.1
info:
  title: Blocks API
  version: v1
paths:
  "/api/formats/{format_id}/files/{file_id}/rows":
    post:
      summary: Creates new row
      tags:
      - Rows
      parameters:
      - name: format_id
        in: path
        required: true
      - name: file_id
        in: path
        required: true
      responses:
        '201':
          description: Row created
    get:
      summary: Retrieves collection of rows
      tags:
      - Rows
      parameters:
      - name: format_id
        in: path
        required: true
      - name: file_id
        in: path
        required: true
      - name: hash
        in: query
        required: false
      - name: state
        in: query
        required: false
      responses:
        '200':
          description: Collection retrieved
    patch:
      summary: Modifies the collection rows
      tags:
      - Rows
      parameters:
      - name: format_id
        in: path
        required: true
      - name: file_id
        in: path
        required: true
      responses:
        '204':
          description: Rows created
  "/api/formats/{format_id}/files/{file_id}/rows/{id}":
    get:
      summary: Retrieves a single row
      tags:
      - Rows
      parameters:
      - name: format_id
        in: path
        required: true
      - name: file_id
        in: path
        required: true
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: Row retrieved
    put:
      summary: Replaces a single row
      tags:
      - Rows
      parameters:
      - name: format_id
        in: path
        required: true
      - name: file_id
        in: path
        required: true
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: Row replaced
    patch:
      summary: Modifies a single row
      tags:
      - Rows
      parameters:
      - name: format_id
        in: path
        required: true
      - name: file_id
        in: path
        required: true
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: Row modified
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
